version: "0.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csbg-test
    restart: unless-stopped
    tty: true
    volumes:
      - appdata:/home/app/src
    networks:
      - frontend
    ports:
      - "5005:5005"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5005/flask-health-check || exit 1" ]
      interval: 20s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: reverse_proxy
    tty: true
    networks:
      - frontend
    restart: unless-stopped
    volumes:
      - nginxdata:/etc/nginx
    environment:
      - APP_BASE_URL=127.0.0.1
      - APP_BASE_PORT=5005
      - NGINX_HOST=127.0.0.1
      - NGINX_port_http=8081
      #- NGINX_port_https=4433
    ports:
      - "8081:8081"
    depends_on:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5005/health-check; || exit 1;" ]
      interval: 20s
      timeout: 10s
      retries: 3

networks:
  frontend:
    driver: bridge

volumes:
  appdata:
    driver: local
  nginxdata:
    driver: local
